//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeWebSite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbResumeEntities : DbContext
    {
        public DbResumeEntities()
            : base("name=DbResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutMe> AboutMe { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Hobbies> Hobbies { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Talents> Talents { get; set; }
        public virtual DbSet<SocialMedia> SocialMedia { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    }
}
